/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/

// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.net.util;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import java.io.ByteArrayOutputStream;

import org.eclipse.kura.KuraException;
import org.eclipse.kura.core.linux.executor.LinuxExitStatus;
import org.eclipse.kura.executor.Command;
import org.eclipse.kura.executor.CommandExecutorService;
import org.eclipse.kura.executor.CommandStatus;
import org.junit.Test;

public class IpAddrShowTest {

    @Test
    public void shouldParseInterfaceWithBothIPv4AndIPv6() throws KuraException {
        CommandExecutorService mockExecutor = mock(CommandExecutorService.class);
        
        CommandStatus linkStatus = createMockCommandStatus(
            "1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default\n" +
            "    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00\n" +
            "2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000\n" +
            "    link/ether aa:bb:cc:dd:ee:ff brd ff:ff:ff:ff:ff:ff"
        );
        
        CommandStatus ipv4Status = createMockCommandStatus(
            "2: eth0    inet *************/*  brd *************scope global eth0\n" +
            "       valid_lft forever preferred_lft forever"
        );
        
        CommandStatus ipv6Status = createMockCommandStatus(
            "2: eth0    inet6 *******************************/ scope global\n" +
            "       valid_lft forever preferred_lft forever\n" +
            "2: eth0    inet6 ************************/  scope link\n" +
            "       valid_lft forever preferred_lft forever"
        );
        
        when(mockExecutor.execute(org.mockito.ArgumentMatchers.argThat(cmd -> 
            String.join(" ", cmd.getCommandLine()).contains("link show"))))
            .thenReturn(linkStatus);
        
        when(mockExecutor.execute(org.mockito.ArgumentMatchers.argThat(cmd -> 
            String.join(" ", cmd.getCommandLine()).contains("-4 addr show"))))
            .thenReturn(ipv4Status);
        
        when(mockExecutor.execute(org.mockito.ArgumentMatchers.argThat(cmd -> 
            String.join(" ", cmd.getCommandLine()).contains("-6 addr show"))))
            .thenReturn(ipv6Status);
        
        IpAddrShow ipAddrShow = new IpAddrShow(mockExecutor);
        LinuxIfconfig[] configs = ipAddrShow.exec();
        
        assertEquals(2, configs.length);
        
        // Find eth0 config
        LinuxIfconfig eth0Config = null;
        for (LinuxIfconfig config : configs) {
            if ("eth0".equals(config.getName())) {
                eth0Config = config;
                break;
            }
        }
        
        assertNotNull(eth0Config);
        assertEquals("*************", eth0Config.getInetAddress());
        assertEquals("*******************************", eth0Config.getInet6Address());
        assertEquals(64, eth0Config.getInet6Prefix());
    }

    @Test
    public void shouldParseInterfaceWithIPv6Only() throws KuraException {
        CommandExecutorService mockExecutor = mock(CommandExecutorService.class);
        
        CommandStatus linkStatus = createMockCommandStatus(
            "2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000\n" +
            "    link/ether aa:bb:cc:dd:ee:ff brd ff:ff:ff:ff:ff:ff"
        );
        
        CommandStatus ipv4Status = createMockCommandStatus("");
        
        CommandStatus ipv6Status = createMockCommandStatus(
            "2: eth0    inet6 *******************************/ scope global\n" +
            "       valid_lft forever preferred_lft forever"
        );
        
        when(mockExecutor.execute(org.mockito.ArgumentMatchers.argThat(cmd -> 
            String.join(" ", cmd.getCommandLine()).contains("link show"))))
            .thenReturn(linkStatus);
        
        when(mockExecutor.execute(org.mockito.ArgumentMatchers.argThat(cmd -> 
            String.join(" ", cmd.getCommandLine()).contains("-4 addr show"))))
            .thenReturn(ipv4Status);
        
        when(mockExecutor.execute(org.mockito.ArgumentMatchers.argThat(cmd -> 
            String.join(" ", cmd.getCommandLine()).contains("-6 addr show"))))
            .thenReturn(ipv6Status);
        
        IpAddrShow ipAddrShow = new IpAddrShow(mockExecutor);
        LinuxIfconfig[] configs = ipAddrShow.exec();
        
        assertEquals(1, configs.length);
        
        LinuxIfconfig eth0Config = configs[0];
        assertEquals("eth0", eth0Config.getName());
        assertNull(eth0Config.getInetAddress());
        assertEquals("*******************************", eth0Config.getInet6Address());
        assertEquals(64, eth0Config.getInet6Prefix());
    }

    @Test
    public void shouldHandleIPv6CommandFailure() throws KuraException {
        CommandExecutorService mockExecutor = mock(CommandExecutorService.class);
        
        CommandStatus linkStatus = createMockCommandStatus(
            "2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000\n" +
            "    link/ether aa:bb:cc:dd:ee:ff brd ff:ff:ff:ff:ff:ff"
        );
        
        CommandStatus ipv4Status = createMockCommandStatus(
            "2: eth0    inet *************/*  brd *************scope global eth0\n" +
            "       valid_lft forever preferred_lft forever"
        );
        
        CommandStatus ipv6Status = new CommandStatus(new Command(new String[]{}), new LinuxExitStatus(1));
        
        when(mockExecutor.execute(org.mockito.ArgumentMatchers.argThat(cmd -> 
            String.join(" ", cmd.getCommandLine()).contains("link show"))))
            .thenReturn(linkStatus);
        
        when(mockExecutor.execute(org.mockito.ArgumentMatchers.argThat(cmd -> 
            String.join(" ", cmd.getCommandLine()).contains("-4 addr show"))))
            .thenReturn(ipv4Status);
        
        when(mockExecutor.execute(org.mockito.ArgumentMatchers.argThat(cmd -> 
            String.join(" ", cmd.getCommandLine()).contains("-6 addr show"))))
            .thenReturn(ipv6Status);
        
        IpAddrShow ipAddrShow = new IpAddrShow(mockExecutor);
        LinuxIfconfig[] configs = ipAddrShow.exec();
        
        assertEquals(1, configs.length);
        
        LinuxIfconfig eth0Config = configs[0];
        assertEquals("eth0", eth0Config.getName());
        assertEquals("*************", eth0Config.getInetAddress());
        assertNull(eth0Config.getInet6Address()); // Should be null due to command failure
        assertEquals(0, eth0Config.getInet6Prefix()); // Should be 0 (default)
    }

    @Test
    public void shouldParseIPv6WithDifferentPrefixLengths() throws KuraException {
        CommandExecutorService mockExecutor = mock(CommandExecutorService.class);
        
        CommandStatus linkStatus = createMockCommandStatus(
            "2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000\n" +
            "    link/ether aa:bb:cc:dd:ee:ff brd ff:ff:ff:ff:ff:ff"
        );
        
        CommandStatus ipv4Status = createMockCommandStatus("");
        
        CommandStatus ipv6Status = createMockCommandStatus(
            "2: eth0    inet6 *******************************/ scope global\n" +
            "       valid_lft forever preferred_lft forever"
        );
        
        when(mockExecutor.execute(org.mockito.ArgumentMatchers.argThat(cmd -> 
            String.join(" ", cmd.getCommandLine()).contains("link show"))))
            .thenReturn(linkStatus);
        
        when(mockExecutor.execute(org.mockito.ArgumentMatchers.argThat(cmd -> 
            String.join(" ", cmd.getCommandLine()).contains("-4 addr show"))))
            .thenReturn(ipv4Status);
        
        when(mockExecutor.execute(org.mockito.ArgumentMatchers.argThat(cmd -> 
            String.join(" ", cmd.getCommandLine()).contains("-6 addr show"))))
            .thenReturn(ipv6Status);
        
        IpAddrShow ipAddrShow = new IpAddrShow(mockExecutor);
        LinuxIfconfig[] configs = ipAddrShow.exec();
        
        assertEquals(1, configs.length);
        
        LinuxIfconfig eth0Config = configs[0];
        assertEquals("eth0", eth0Config.getName());
        assertEquals("*******************************", eth0Config.getInet6Address());
        assertEquals(48, eth0Config.getInet6Prefix());
    }

    private CommandStatus createMockCommandStatus(String output) {
        CommandStatus status = new CommandStatus(new Command(new String[]{}), new LinuxExitStatus(0));
        ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
        try {
            outputStream.write(output.getBytes());
        } catch (Exception e) {
            // Ignore
        }
        status.setOutputStream(outputStream);
        return status;
    }
}
