/*******************************************************************************
 * Copyright (c) 2025 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/

// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.net.util;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNull;
import static org.junit.Assert.assertTrue;

import org.junit.Test;

public class LinuxIfconfigTest {

    @Test
    public void shouldSetAndGetInet6Address() {
        LinuxIfconfig config = new LinuxIfconfig("eth0");
        
        config.setInet6Address("*******************************");
        
        assertEquals("*******************************", config.getInet6Address());
    }

    @Test
    public void shouldSetAndGetInet6Prefix() {
        LinuxIfconfig config = new LinuxIfconfig("eth0");
        
        config.setInet6Prefix(64);
        
        assertEquals(64, config.getInet6Prefix());
    }

    @Test
    public void shouldReturnNullInet6AddressWhenNotSet() {
        LinuxIfconfig config = new LinuxIfconfig("eth0");
        
        assertNull(config.getInet6Address());
    }

    @Test
    public void shouldReturnZeroInet6PrefixWhenNotSet() {
        LinuxIfconfig config = new LinuxIfconfig("eth0");
        
        assertEquals(0, config.getInet6Prefix());
    }

    @Test
    public void shouldBeUpWhenExplicitlySet() {
        LinuxIfconfig config = new LinuxIfconfig("eth0");
        
        config.setUp(true);
        
        assertTrue(config.isUp());
    }

    @Test
    public void shouldBeDownWhenExplicitlySet() {
        LinuxIfconfig config = new LinuxIfconfig("eth0");
        
        config.setUp(false);
        
        assertFalse(config.isUp());
    }

    @Test
    public void shouldBeUpWhenHasIPv4AddressAndMask() {
        LinuxIfconfig config = new LinuxIfconfig("eth0");
        
        config.setInetAddress("*************");
        config.setInetMask("*************");
        
        assertTrue(config.isUp());
    }

    @Test
    public void shouldBeUpWhenHasIPv6Address() {
        LinuxIfconfig config = new LinuxIfconfig("eth0");
        
        config.setInet6Address("*******************************");
        config.setInet6Prefix(64);
        
        assertTrue(config.isUp());
    }

    @Test
    public void shouldBeUpWhenHasBothIPv4AndIPv6() {
        LinuxIfconfig config = new LinuxIfconfig("eth0");
        
        config.setInetAddress("*************");
        config.setInetMask("*************");
        config.setInet6Address("*******************************");
        config.setInet6Prefix(64);
        
        assertTrue(config.isUp());
    }

    @Test
    public void shouldBeDownWhenHasOnlyIPv4AddressButNoMask() {
        LinuxIfconfig config = new LinuxIfconfig("eth0");
        
        config.setInetAddress("*************");
        
        assertFalse(config.isUp());
    }

    @Test
    public void shouldBeDownWhenHasOnlyIPv4MaskButNoAddress() {
        LinuxIfconfig config = new LinuxIfconfig("eth0");
        
        config.setInetMask("*************");
        
        assertFalse(config.isUp());
    }

    @Test
    public void shouldBeDownWhenHasNoAddresses() {
        LinuxIfconfig config = new LinuxIfconfig("eth0");
        
        assertFalse(config.isUp());
    }

    @Test
    public void shouldPreferExplicitUpFlagOverAddresses() {
        LinuxIfconfig config = new LinuxIfconfig("eth0");
        
        config.setInet6Address("*******************************");
        config.setInet6Prefix(64);
        
        config.setUp(false);
        
        assertFalse(config.isUp());
    }

    @Test
    public void shouldPreferExplicitDownFlagOverAddresses() {
        LinuxIfconfig config = new LinuxIfconfig("eth0");
        
        config.setUp(true);
        
        assertTrue(config.isUp());
    }
}
