/*******************************************************************************
 * Copyright (c) 2025, 2026 Eurotech and/or its affiliates and others
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 *
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.net.iptables;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertTrue;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;

import java.net.UnknownHostException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;
import org.eclipse.kura.KuraException;
import org.eclipse.kura.KuraIOException;
import org.eclipse.kura.net.IP4Address;
import org.eclipse.kura.net.IPAddress;
import org.eclipse.kura.net.NetworkPair;
import org.eclipse.kura.net.firewall.RuleType;
import org.junit.Before;
import org.junit.Test;

/**
 * Test class for AbstractLinuxFirewall ICMP rule detection functionality.
 * This feature verifies that ICMP rules in additional rules prevent allowIcmp
 * from being set.
 */
public class AbstractLinuxFirewallTest {

    private TestableAbstractLinuxFirewall firewall;
    private IptablesConfig mockIptablesConfig;
    private Set<String> filterRules;
    private Set<String> natRules;
    private Set<String> mangleRules;
    private List<LocalRule> newLocalRules;
    private List<PortForwardRule> newPortForwardRules;
    private List<NATRule> newNatRules;
    private Exception thrownException;

    @Before
    public void setUp() {
        this.mockIptablesConfig = mock(IptablesConfig.class);
        this.firewall = new TestableAbstractLinuxFirewall();
        this.firewall.iptables = this.mockIptablesConfig;
        this.filterRules = new HashSet<>();
        this.natRules = new HashSet<>();
        this.mangleRules = new HashSet<>();
    }

    @Test
    public void setAdditionalRulesWithIcmpRulesInFilter() throws KuraException {
        givenAdditionalRulesWithIcmpInFilter();

        whenSettingAdditionalRules();

        thenAllowIcmpIsFalse();
    }

    @Test
    public void setAdditionalRulesWithIcmpRulesInNat() throws KuraException {
        givenAdditionalRulesWithIcmpInNat();

        whenSettingAdditionalRules();

        thenAllowIcmpIsFalse();
    }

    @Test
    public void setAdditionalRulesWithIcmpRulesInMangle() throws KuraException {
        givenAdditionalRulesWithIcmpInMangle();

        whenSettingAdditionalRules();

        thenAllowIcmpIsFalse();
    }

    @Test
    public void setAdditionalRulesWithoutIcmpRules() throws KuraException {
        givenAdditionalRulesWithoutIcmp();

        whenSettingAdditionalRules();

        thenAllowIcmpIsTrue();
    }

    @Test
    public void setAdditionalRulesWithEmptyRules() throws KuraException {
        givenEmptyAdditionalRules();

        whenSettingAdditionalRules();

        thenAllowIcmpIsTrue();
    }

    @Test
    public void replacingRulesReplacesLocalPortForwardAndNatRules() throws KuraException, UnknownHostException {
        givenExistingLocalPortForwardAndNatRules();

        whenReplacingLocalPortForwardAndNatRules();

        thenLocalPortForwardAndNatRulesAreReplaced();
    }

    @Test
    public void blockingAllPortsClearsLocalPortForwardNatAndAutoNatRules() throws KuraException, UnknownHostException {
        givenExistingLocalPortForwardAndNatRules();
        givenExistingAutoNatRule();

        whenBlockingAllPorts();

        thenAllRuleSetsAreEmpty();
    }

    @Test
    public void unblockingAllPortsThrowsUnsupportedOperationException() {
        whenUnblockingAllPorts();

        thenUnsupportedOperationExceptionWasThrown();
    }

    // Given methods

    private void givenExistingLocalPortForwardAndNatRules() throws KuraException, UnknownHostException {
        try {
            this.firewall.addLocalRules(Arrays.asList(newLocalRule(5400)));
        } catch (KuraIOException e) {
            // Do nothing...
        }
        try {
            this.firewall.addPortForwardRules(Arrays.asList(newPortForwardRule(4040)));
        } catch (KuraIOException e) {
            // Do nothing...
        }
        try {
            this.firewall.addNatRules(Arrays.asList(newNatRule("eth0", "eth1")));
        } catch (KuraIOException e) {
            // Do nothing...
        }
    }

    private void givenExistingAutoNatRule() throws KuraException {
        try {
            this.firewall.addAutoNatRules(Arrays.asList(newNatRule("eth4", "eth5")));
        } catch (KuraIOException e) {
            // Do nothing...
        }
    }

    private LocalRule newLocalRule(int port) throws UnknownHostException {
        return new LocalRule(
                port,
                "tcp",
                new NetworkPair<>((IP4Address) IPAddress.parseHostAddress("0.0.0.0"), (short) 0),
                "eth0",
                null,
                "00:11:22:33:44:55:66",
                "10100:10200");
    }

    private PortForwardRule newPortForwardRule(int inPort) {
        return new PortForwardRule()
                .inboundIface("eth0")
                .outboundIface("eth1")
                .address("172.16.0.1")
                .protocol("tcp")
                .inPort(inPort)
                .outPort(4050)
                .masquerade(true)
                .permittedNetwork("172.16.0.100")
                .permittedNetworkMask(32);
    }

    private NATRule newNatRule(String sourceInterface, String destinationInterface) {
        return new NATRule(sourceInterface, destinationInterface, null, null, null, true, RuleType.GENERIC);
    }

    private void givenAdditionalRulesWithIcmpInFilter() {
        this.filterRules.add("-A input-kura -p icmp --icmp-type 8 -j DROP");
        this.filterRules.add("-A input-kura -p tcp --dport 80 -j ACCEPT");
    }

    private void givenAdditionalRulesWithIcmpInNat() {
        this.natRules.add("-A prerouting-kura --protocol ipv6-icmp --icmpv6-type 129 -j DROP");
        this.natRules.add("-A prerouting-kura -p tcp --dport 443 -j ACCEPT");
    }

    private void givenAdditionalRulesWithIcmpInMangle() {
        this.mangleRules.add(
                "-A prerouting-kura -p icmp -m icmp --icmp-type 8 -m state --state NEW,RELATED,ESTABLISHED -j DROP");
        this.mangleRules.add("-A prerouting-kura -p tcp --tcp-flags SYN,RST SYN,RST -j DROP");
    }

    private void givenAdditionalRulesWithoutIcmp() {
        this.filterRules.add("-A input-kura -p tcp --dport 80 -j ACCEPT");
        this.natRules.add("-A prerouting-kura -p tcp --dport 443 -j ACCEPT");
        this.mangleRules.add("-A prerouting-kura -p tcp --tcp-flags SYN,RST SYN,RST -j DROP");
    }

    private void givenEmptyAdditionalRules() {
        // filterRules, natRules, and mangleRules are already empty
    }

    // When methods

    private void whenSettingAdditionalRules() throws KuraException {
        this.firewall.setAdditionalRules(this.filterRules, this.natRules, this.mangleRules);
    }

    private void whenReplacingLocalPortForwardAndNatRules() throws KuraException, UnknownHostException {
        this.newLocalRules = Arrays.asList(newLocalRule(5401));
        this.newPortForwardRules = Arrays.asList(newPortForwardRule(4041));
        this.newNatRules = Arrays.asList(newNatRule("eth2", "eth3"));

        try {
            this.firewall.replace(this.newLocalRules, this.newPortForwardRules, this.newNatRules);
        } catch (KuraIOException e) {
            // Do nothing...
        }
    }

    private void whenBlockingAllPorts() throws KuraException {
        try {
            this.firewall.blockAllPorts();
        } catch (KuraIOException e) {
            // Do nothing...
        }
    }

    private void whenUnblockingAllPorts() {
        try {
            this.firewall.unblockAllPorts();
        } catch (Exception e) {
            this.thrownException = e;
        }
    }

    // Then methods

    private void thenAllowIcmpIsFalse() {
        verify(this.mockIptablesConfig, times(1)).setAllowIcmp(false);
    }

    private void thenAllowIcmpIsTrue() {
        verify(this.mockIptablesConfig, times(1)).setAllowIcmp(true);
    }

    private void thenLocalPortForwardAndNatRulesAreReplaced() {
        assertEquals(new LinkedHashSet<>(this.newLocalRules), this.firewall.getLocalRules());
        assertEquals(new LinkedHashSet<>(this.newPortForwardRules), this.firewall.getPortForwardRules());
        assertEquals(new LinkedHashSet<>(this.newNatRules), this.firewall.getNatRules());
    }

    private void thenAllRuleSetsAreEmpty() {
        assertTrue(this.firewall.getLocalRules().isEmpty());
        assertTrue(this.firewall.getPortForwardRules().isEmpty());
        assertTrue(this.firewall.getNatRules().isEmpty());
        assertTrue(this.firewall.getAutoNatRules().isEmpty());
    }

    private void thenUnsupportedOperationExceptionWasThrown() {
        assertTrue(this.thrownException instanceof UnsupportedOperationException);
    }

    /**
     * Testable implementation of AbstractLinuxFirewall for testing purposes.
     */
    private static class TestableAbstractLinuxFirewall extends AbstractLinuxFirewall {

        public TestableAbstractLinuxFirewall() {
            super();
            this.allowIcmp = false;
        }

        @Override
        protected IPAddress getDefaultAddress() throws UnknownHostException {
            return IPAddress.parseHostAddress("0.0.0.0");
        }

        @Override
        protected String getIpForwardFileName() {
            return "/proc/sys/net/ipv4/ip_forward";
        }
    }
}
