/*******************************************************************************
 * Copyright (c) 2020, 2025 Eurotech and/or its affiliates and others
 * 
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 * 
 * SPDX-License-Identifier: EPL-2.0
 * 
 * Contributors:
 *  Eurotech
 *******************************************************************************/
// Content with portions generated by generative AI platform
package org.eclipse.kura.linux.net.iptables;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertSame;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.atLeast;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.Set;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.stream.Stream;

import org.eclipse.kura.KuraException;
import org.eclipse.kura.KuraIOException;
import org.eclipse.kura.core.linux.executor.LinuxExitStatus;
import org.eclipse.kura.executor.Command;
import org.eclipse.kura.executor.CommandExecutorService;
import org.eclipse.kura.executor.CommandStatus;
import org.eclipse.kura.net.IP4Address;
import org.eclipse.kura.net.IPAddress;
import org.eclipse.kura.net.NetworkPair;
import org.eclipse.kura.net.firewall.RuleType;
import org.junit.Test;

public class IpTablesConfigTest extends FirewallTestUtils {

    @Test
    public void clearAllChainsTest() throws KuraException {
        setUpMock();
        IptablesConfig iptablesConfig = new IptablesConfig(executorServiceMock);
        iptablesConfig.clearAllChains();

        verify(executorServiceMock, times(1)).execute(commandRestoreTmp);
    }

    @Test
    public void applyBlockPolicyTest() throws KuraException {
        setUpMock();
        IptablesConfig iptablesConfig = new IptablesConfig(executorServiceMock);
        iptablesConfig.applyBlockPolicy();

        verify(executorServiceMock, times(1)).execute(commandRestoreTmp);
    }

    @Test
    public void clearAllKuraChainsTest() {
        setUpMock();
        IptablesConfig iptablesConfig = new IptablesConfig(executorServiceMock);
        iptablesConfig.clearAllKuraChains();

        verify(executorServiceMock, times(1)).execute(commandFlushInputFilter);
        verify(executorServiceMock, times(1)).execute(commandFlushOutputFilter);
        verify(executorServiceMock, times(1)).execute(commandFlushForwardFilter);
        verify(executorServiceMock, times(1)).execute(commandFlushInputNat);
        verify(executorServiceMock, times(1)).execute(commandFlushOutputNat);
        verify(executorServiceMock, times(1)).execute(commandFlushPreroutingNat);
        verify(executorServiceMock, times(1)).execute(commandFlushPostroutingNat);
    }

    @Test
    public void saveTest() {
        setUpMock();
        IptablesConfig iptablesConfig = new IptablesConfig(executorServiceMock);
        iptablesConfig.save();

        verify(executorServiceMock, times(1)).execute(commandSave);
    }

    @Test
    public void saveWithFilenameTest() {
        setUpMock();

        IptablesConfig iptablesConfig = new IptablesConfig(executorServiceMock);
        iptablesConfig.save(iptablesConfig.getFirewallConfigTmpFileName());

        verify(executorServiceMock, times(1)).execute(commandSaveTmp);
    }

    @Test
    public void restoreWithFilenameTest() {
        setUpMock();
        IptablesConfig iptablesConfig = new IptablesConfig(executorServiceMock);
        iptablesConfig.restore(iptablesConfig.getFirewallConfigFileName());

        verify(executorServiceMock, times(1)).execute(commandRestore);
    }

    @Test
    public void saveKuraChainsTest() throws KuraException, IOException {
        setUpMock();
        Set<LocalRule> localRules = new LinkedHashSet<>();
        localRules.add(new LocalRule(5400, "tcp",
                new NetworkPair<>((IP4Address) IPAddress.parseHostAddress("0.0.0.0"), (short) 0), "eth0", null,
                "00:11:22:33:44:55:66", "10100:10200"));

        Set<PortForwardRule> portForwardRules = new LinkedHashSet<>();
        PortForwardRule portForwardRule = new PortForwardRule().inboundIface("eth0").outboundIface("eth1")
                .address("172.16.0.1").addressMask(32).protocol("tcp").inPort(3040).outPort(4050).masquerade(true)
                .permittedNetwork("172.16.0.100").permittedNetworkMask(32).permittedMAC("00:11:22:33:44:55:66")
                .sourcePortRange("10100:10200");
        portForwardRules.add(portForwardRule);

        Set<NATRule> autoNatRules = new LinkedHashSet<>();
        autoNatRules.add(new NATRule("eth2", "eth3", true, RuleType.GENERIC));

        Set<NATRule> natRules = new LinkedHashSet<>();
        natRules.add(
                new NATRule("eth4", "eth5", "tcp", "172.16.0.1/24", "172.16.0.2/24", true, RuleType.IP_FORWARDING));

        IptablesConfig iptablesConfig = new IptablesConfig(localRules, portForwardRules, autoNatRules, natRules, true,
                executorServiceMock);

        try {
            iptablesConfig.saveKuraChains();
        } catch (KuraIOException e) {
            // do nothing...
        }

        AtomicBoolean isLocalRulePresent = new AtomicBoolean(false);
        AtomicBoolean[] isPortForwardRulePresent = { new AtomicBoolean(false), new AtomicBoolean(false),
                new AtomicBoolean(false), new AtomicBoolean(false) };
        AtomicBoolean[] isAutoNatRulePresent = { new AtomicBoolean(false), new AtomicBoolean(false),
                new AtomicBoolean(false) };
        AtomicBoolean[] isNatRulePresent = { new AtomicBoolean(false), new AtomicBoolean(false),
                new AtomicBoolean(false) };
        try (Stream<String> lines = Files.lines(Paths.get(iptablesConfig.getFirewallConfigTmpFileName()))) {
            lines.forEach(line -> {
                line = line.trim();
                switch (line) {
                    case "-A input-kura -p tcp -s 0.0.0.0/0 -i eth0 -m mac --mac-source 00:11:22:33:44:55:66 --sport 10100:10200 --dport 5400 -j ACCEPT":
                        isLocalRulePresent.set(true);
                        break;
                    case "-A forward-kura-pf -s 172.16.0.100/32 -d 172.16.0.1/32 -i eth0 -o eth1 -p tcp -m tcp -m mac --mac-source 00:11:22:33:44:55:66 --sport 10100:10200 -j ACCEPT":
                        isPortForwardRulePresent[0].set(true);
                        break;
                    case "-A forward-kura-pf -s 172.16.0.1/32 -i eth1 -o eth0 -p tcp -m state --state RELATED,ESTABLISHED -j ACCEPT":
                        isPortForwardRulePresent[1].set(true);
                        break;
                    case "-A prerouting-kura-pf -s 172.16.0.100/32 -i eth0 -p tcp -m mac --mac-source 00:11:22:33:44:55:66 -m tcp --sport 10100:10200 --dport 3040 -j DNAT --to-destination 172.16.0.1:4050":
                        isPortForwardRulePresent[2].set(true);
                        break;
                    case "-A postrouting-kura-pf -s 172.16.0.100/32 -d 172.16.0.1/32 -o eth1 -p tcp -j MASQUERADE":
                        isPortForwardRulePresent[3].set(true);
                        break;
                    case "-A forward-kura -i eth2 -o eth3 -j ACCEPT":
                        isAutoNatRulePresent[0].set(true);
                        break;
                    case "-A forward-kura -i eth3 -o eth2 -m state --state RELATED,ESTABLISHED -j ACCEPT":
                        isAutoNatRulePresent[1].set(true);
                        break;
                    case "-A postrouting-kura -o eth3 -j MASQUERADE":
                        isAutoNatRulePresent[2].set(true);
                        break;
                    case "-A postrouting-kura-ipf -s 172.16.0.1/24 -d 172.16.0.2/24 -o eth5 -p tcp -j MASQUERADE":
                        isNatRulePresent[0].set(true);
                        break;
                    case "-A forward-kura-ipf -s 172.16.0.1/24 -d 172.16.0.2/24 -i eth4 -o eth5 -p tcp -m tcp -j ACCEPT":
                        isNatRulePresent[1].set(true);
                        break;
                    case "-A forward-kura-ipf -s 172.16.0.2/24 -i eth5 -o eth4 -p tcp -m state --state RELATED,ESTABLISHED -j ACCEPT":
                        isNatRulePresent[2].set(true);
                        break;
                }

            });
        } catch (IOException e) {
            throw new KuraIOException(e, "save() :: failed to save rules on file");
        }
        assertTrue(isLocalRulePresent.get());
        assertTrue(isPortForwardRulePresent[0].get() && isPortForwardRulePresent[1].get()
                && isPortForwardRulePresent[2].get() && isPortForwardRulePresent[3].get());
        assertTrue(isAutoNatRulePresent[0].get() && isAutoNatRulePresent[1].get() && isAutoNatRulePresent[2].get());
        assertTrue(isNatRulePresent[0].get() && isNatRulePresent[1].get() && isNatRulePresent[2].get());

        File configFile = new File(iptablesConfig.getFirewallConfigTmpFileName());
        Files.deleteIfExists(configFile.toPath());

    }

    @Test
    public void applyRulesTest() {
        setUpMock();

        String[] mangleRulesArray = { "-A prerouting-kura -m conntrack --ctstate INVALID -j DROP",
                "-A prerouting-kura -p tcp ! --syn -m conntrack --ctstate NEW -j DROP",
                "-A prerouting-kura -p tcp -m conntrack --ctstate NEW -m tcpmss ! --mss 536:65535 -j DROP",
                "-A prerouting-kura -p tcp --tcp-flags FIN,SYN FIN,SYN -j DROP",
                "-A prerouting-kura -p tcp --tcp-flags SYN,RST SYN,RST -j DROP",
                "-A prerouting-kura -p tcp --tcp-flags FIN,RST FIN,RST -j DROP",
                "-A prerouting-kura -p tcp --tcp-flags FIN,ACK FIN -j DROP",
                "-A prerouting-kura -p tcp --tcp-flags ACK,URG URG -j DROP",
                "-A prerouting-kura -p tcp --tcp-flags ACK,FIN FIN -j DROP",
                "-A prerouting-kura -p tcp --tcp-flags ACK,PSH PSH -j DROP",
                "-A prerouting-kura -p tcp --tcp-flags ALL ALL -j DROP",
                "-A prerouting-kura -p tcp --tcp-flags ALL NONE -j DROP",
                "-A prerouting-kura -p tcp --tcp-flags ALL FIN,PSH,URG -j DROP",
                "-A prerouting-kura -p tcp --tcp-flags ALL SYN,FIN,PSH,URG -j DROP",
                "-A prerouting-kura -p tcp --tcp-flags ALL SYN,RST,ACK,FIN,URG -j DROP",
                "-A prerouting-kura -p icmp -j DROP", "-A prerouting-kura -f -j DROP" };
        Set<String> mangleRules = new HashSet<String>(Arrays.asList(mangleRulesArray));

        // These rules are fake...
        String[] filterRulesArray = { "-A input-kura -p tcp -f -j DROP" };
        Set<String> filterRules = new HashSet<String>(Arrays.asList(filterRulesArray));

        // Also these ones...
        String[] natRulesArray = { "-A prerouting-kura -p tcp -f -j DROP" };
        Set<String> natRules = new HashSet<String>(Arrays.asList(natRulesArray));

        IptablesConfig iptablesConfig = new IptablesConfig(new LinkedHashSet<>(), new LinkedHashSet<>(),
                new LinkedHashSet<>(), new LinkedHashSet<>(), false, executorServiceMock);
        iptablesConfig.setAdditionalFilterRules(filterRules);
        iptablesConfig.setAdditionalNatRules(natRules);
        iptablesConfig.setAdditionalMangleRules(mangleRules);
        iptablesConfig.applyRules();

        for (Command c : commandApplyList) {
            System.out.println(c);
            verify(executorServiceMock, atLeast(1)).execute(c);
        }
    }

    @Test
    public void shouldRestoreConfig() throws KuraException, IOException {
        IptablesConfig iptablesConfig = new IptablesConfig() {
            @Override
            public String getFirewallConfigFileName() {
                return getFirewallConfigTmpFileName();
            }
        };

        BufferedWriter writer = new BufferedWriter(new FileWriter(iptablesConfig.getFirewallConfigTmpFileName()));
        writer.write(FirewallTestUtils.IPTABLES_FILE_CONTENT);
        writer.close();

        iptablesConfig.restore();

        assertEquals(10, iptablesConfig.localRules.size());
        assertEquals(1, iptablesConfig.portForwardRules.size());
        assertEquals(1, iptablesConfig.natRules.size());
        assertEquals(1, iptablesConfig.autoNatRules.size());

        File configFile = new File(iptablesConfig.getFirewallConfigTmpFileName());
        Files.deleteIfExists(configFile.toPath());
    }

    @Test
    public void testDefaultConstructor() {
        IptablesConfig config = new IptablesConfig();

        assertNotNull("Local rules should not be null", config.getLocalRules());
        assertNotNull("Port forward rules should not be null", config.getPortForwardRules());
        assertNotNull("Auto NAT rules should not be null", config.getAutoNatRules());
        assertNotNull("NAT rules should not be null", config.getNatRules());
        assertNotNull("Additional filter rules should not be null", config.getAdditionalFilterRules());
        assertNotNull("Additional NAT rules should not be null", config.getAdditionalNatRules());
        assertNotNull("Additional mangle rules should not be null", config.getAdditionalMangleRules());
        assertTrue("ICMP should be allowed by default", config.allowIcmp());
    }

    @Test
    public void testConstructorWithExecutorService() {
        CommandExecutorService mockService = mock(CommandExecutorService.class);
        IptablesConfig config = new IptablesConfig(mockService);

        assertNotNull("Local rules should not be null", config.getLocalRules());
        assertNotNull("Port forward rules should not be null", config.getPortForwardRules());
        assertNotNull("Auto NAT rules should not be null", config.getAutoNatRules());
        assertNotNull("NAT rules should not be null", config.getNatRules());
        assertTrue("ICMP should be allowed by default", config.allowIcmp());
    }

    @Test
    public void testFullConstructor() {
        Set<LocalRule> localRules = new LinkedHashSet<>();
        Set<PortForwardRule> portForwardRules = new LinkedHashSet<>();
        Set<NATRule> autoNatRules = new LinkedHashSet<>();
        Set<NATRule> natRules = new LinkedHashSet<>();
        CommandExecutorService mockService = mock(CommandExecutorService.class);
        boolean allowIcmp = false;

        IptablesConfig config = new IptablesConfig(localRules, portForwardRules,
                autoNatRules, natRules, allowIcmp, mockService);

        assertSame("Local rules should be the same instance", localRules, config.getLocalRules());
        assertSame("Port forward rules should be the same instance", portForwardRules, config.getPortForwardRules());
        assertSame("Auto NAT rules should be the same instance", autoNatRules, config.getAutoNatRules());
        assertSame("NAT rules should be the same instance", natRules, config.getNatRules());
        assertFalse("ICMP should be disabled", config.allowIcmp());
        assertNotNull("Additional filter rules should be initialized", config.getAdditionalFilterRules());
        assertNotNull("Additional NAT rules should be initialized", config.getAdditionalNatRules());
        assertNotNull("Additional mangle rules should be initialized", config.getAdditionalMangleRules());
    }

    @Test
    public void testGetters() {
        IptablesConfig config = new IptablesConfig();

        assertNotNull("getFirewallConfigFileName should not return null", config.getFirewallConfigFileName());
        assertNotNull("getFirewallConfigTmpFileName should not return null", config.getFirewallConfigTmpFileName());
        assertTrue("getFirewallConfigFileName should contain iptables",
                config.getFirewallConfigFileName().contains("iptables"));
        assertTrue("getFirewallConfigTmpFileName should contain tmp",
                config.getFirewallConfigTmpFileName().contains("tmp"));
    }

    @Test
    public void testSettersAndGetters() {
        IptablesConfig config = new IptablesConfig();

        // Test local rules
        Set<LocalRule> newLocalRules = new LinkedHashSet<>();
        config.setLocalRules(newLocalRules);
        assertSame("Local rules should be updated", newLocalRules, config.getLocalRules());

        // Test port forward rules
        Set<PortForwardRule> newPortForwardRules = new LinkedHashSet<>();
        config.setPortForwardRules(newPortForwardRules);
        assertSame("Port forward rules should be updated", newPortForwardRules, config.getPortForwardRules());

        // Test auto NAT rules
        Set<NATRule> newAutoNatRules = new LinkedHashSet<>();
        config.setAutoNatRules(newAutoNatRules);
        assertSame("Auto NAT rules should be updated", newAutoNatRules, config.getAutoNatRules());

        // Test NAT rules
        Set<NATRule> newNatRules = new LinkedHashSet<>();
        config.setNatRules(newNatRules);
        assertSame("NAT rules should be updated", newNatRules, config.getNatRules());

        // Test additional filter rules
        Set<String> newFilterRules = new LinkedHashSet<>();
        newFilterRules.add("-A input-kura -p tcp --dport 8080 -j ACCEPT");
        config.setAdditionalFilterRules(newFilterRules);
        assertSame("Additional filter rules should be updated", newFilterRules, config.getAdditionalFilterRules());

        // Test additional NAT rules
        Set<String> newNatRulesSet = new LinkedHashSet<>();
        newNatRulesSet.add("-A postrouting-kura -o eth1 -j MASQUERADE");
        config.setAdditionalNatRules(newNatRulesSet);
        assertSame("Additional NAT rules should be updated", newNatRulesSet, config.getAdditionalNatRules());

        // Test additional mangle rules
        Set<String> newMangleRules = new LinkedHashSet<>();
        newMangleRules.add("-A prerouting-kura -p tcp --dport 80 -j MARK --set-mark 1");
        config.setAdditionalMangleRules(newMangleRules);
        assertSame("Additional mangle rules should be updated", newMangleRules, config.getAdditionalMangleRules());

        // Test ICMP settings
        config.setAllowIcmp(false);
        assertFalse("ICMP should be disabled", config.allowIcmp());

        config.setAllowIcmp(true);
        assertTrue("ICMP should be enabled", config.allowIcmp());
    }

    @Test
    public void testIcmpArrayMethods() {
        IptablesConfig config = new IptablesConfig();

        String[] allowIcmp = config.getAllowIcmp();
        assertNotNull("getAllowIcmp should not return null", allowIcmp);
        assertTrue("getAllowIcmp should return non-empty array", allowIcmp.length > 0);

        String[] notAllowIcmp = config.getNotAllowIcmp();
        assertNotNull("getNotAllowIcmp should not return null", notAllowIcmp);
        assertTrue("getNotAllowIcmp should return non-empty array", notAllowIcmp.length > 0);
    }

    @Test(expected = KuraIOException.class)
    public void testClearAllChainsIOException() throws KuraException {
        // Create a config that will cause an IOException when writing to file
        IptablesConfig config = new IptablesConfig(mock(CommandExecutorService.class)) {
            @Override
            public String getFirewallConfigTmpFileName() {
                return "/invalid/path/that/does/not/exist/iptables.tmp";
            }
        };

        config.clearAllChains();
    }

    @Test(expected = KuraIOException.class)
    public void testApplyBlockPolicyIOException() throws KuraException {
        // Create a config that will cause an IOException when writing to file
        IptablesConfig config = new IptablesConfig(mock(CommandExecutorService.class)) {
            @Override
            public String getFirewallConfigTmpFileName() {
                return "/invalid/path/that/does/not/exist/iptables.tmp";
            }
        };

        config.applyBlockPolicy();
    }

    @Test
    public void testClearAllKuraChainsWithNullExecutorService() {
        IptablesConfig config = new IptablesConfig(); // No executor service

        // Should not throw an exception, just log an error
        config.clearAllKuraChains();
    }

    @Test(expected = IllegalArgumentException.class)
    public void testSaveWithNullExecutorService() {
        IptablesConfig config = new IptablesConfig(); // No executor service
        config.save();
    }

    @Test(expected = IllegalArgumentException.class)
    public void testRestoreWithNullExecutorService() {
        IptablesConfig config = new IptablesConfig(); // No executor service
        config.restore("test-file");
    }

    @Test
    public void testSaveKuraChainsWithEmptyRules() throws KuraException, IOException {
        setUpMock();
        IptablesConfig config = new IptablesConfig(executorServiceMock);

        // All rule sets are empty by default
        try {
            config.saveKuraChains();
        } catch (KuraIOException e) {
            // Expected if file operations fail, but the method should handle empty rules
        }

        // Verify the temporary file was created
        File tempFile = new File(config.getFirewallConfigTmpFileName());
        if (tempFile.exists()) {
            // Verify file content contains expected sections even with empty rules
            try (Stream<String> lines = Files.lines(tempFile.toPath())) {
                String content = String.join("\n", lines.toList());
                assertTrue("File should contain *filter section", content.contains("*filter"));
                assertTrue("File should contain *nat section", content.contains("*nat"));
                assertTrue("File should contain COMMIT statements", content.contains("COMMIT"));
                assertTrue("File should contain input-kura chain", content.contains("input-kura"));
            }

            Files.deleteIfExists(tempFile.toPath());
        } else {
            // If the file wasn't created due to test environment limitations,
            // at least verify the executor was called
            verify(executorServiceMock, atLeast(1)).execute(any(Command.class));
        }
    }

    @Test
    public void testRestoreWithNonExistentFile() throws KuraException {
        IptablesConfig config = new IptablesConfig() {
            @Override
            public String getFirewallConfigFileName() {
                return "/non/existent/file.conf";
            }
        };

        // Should return immediately without error if file doesn't exist
        config.restore();

        // Verify rules remain empty
        assertTrue("Local rules should be empty", config.getLocalRules().isEmpty());
        assertTrue("Port forward rules should be empty", config.getPortForwardRules().isEmpty());
        assertTrue("NAT rules should be empty", config.getNatRules().isEmpty());
        assertTrue("Auto NAT rules should be empty", config.getAutoNatRules().isEmpty());
    }

    @Test
    public void testApplyRulesWithFailedCommands() {
        CommandExecutorService mockService = mock(CommandExecutorService.class);
        CommandStatus failedStatus = new CommandStatus(new Command(new String[] {}),
                new LinuxExitStatus(1));
        when(mockService.execute(any(Command.class))).thenReturn(failedStatus);

        IptablesConfig config = new IptablesConfig(mockService);

        // Should not throw exception even if commands fail
        config.applyRules();

        // Verify that execute was called multiple times (for various commands)
        verify(mockService, atLeast(10)).execute(any(Command.class));
    }

    @Test
    public void testSaveKuraChainsWithAdditionalRules() throws KuraException, IOException {
        setUpMock();

        Set<String> additionalFilterRules = new LinkedHashSet<>();
        additionalFilterRules.add("-A input-kura -p tcp --dport 8080 -j ACCEPT");
        additionalFilterRules.add("-A input-kura -p tcp --dport 9090 -j ACCEPT");

        Set<String> additionalNatRules = new LinkedHashSet<>();
        additionalNatRules.add("-A postrouting-kura -o eth2 -j MASQUERADE");

        Set<String> additionalMangleRules = new LinkedHashSet<>();
        additionalMangleRules.add("-A prerouting-kura -p tcp --dport 80 -j MARK --set-mark 1");

        IptablesConfig config = new IptablesConfig(executorServiceMock);
        config.setAdditionalFilterRules(additionalFilterRules);
        config.setAdditionalNatRules(additionalNatRules);
        config.setAdditionalMangleRules(additionalMangleRules);

        try {
            config.saveKuraChains();
        } catch (KuraIOException e) {
            // Expected if file operations fail
        }

        // Verify additional rules are written to the configuration
        File tempFile = new File(config.getFirewallConfigTmpFileName());
        if (tempFile.exists()) {
            try (Stream<String> lines = Files.lines(tempFile.toPath())) {
                AtomicBoolean foundFilterRule = new AtomicBoolean(false);
                AtomicBoolean foundNatRule = new AtomicBoolean(false);
                AtomicBoolean foundMangleRule = new AtomicBoolean(false);

                lines.forEach(line -> {
                    if (line.contains("-A input-kura -p tcp --dport 8080 -j ACCEPT")) {
                        foundFilterRule.set(true);
                    }
                    if (line.contains("-A postrouting-kura -o eth2 -j MASQUERADE")) {
                        foundNatRule.set(true);
                    }
                    if (line.contains("-A prerouting-kura -p tcp --dport 80 -j MARK --set-mark 1")) {
                        foundMangleRule.set(true);
                    }
                });

                assertTrue("Additional filter rule should be present", foundFilterRule.get());
                assertTrue("Additional NAT rule should be present", foundNatRule.get());
                assertTrue("Additional mangle rule should be present", foundMangleRule.get());
            }
            Files.deleteIfExists(tempFile.toPath());
        }
    }

    @Test
    public void testSaveKuraChainsWithDisallowedIcmp() throws KuraException, IOException {
        setUpMock();
        IptablesConfig config = new IptablesConfig(executorServiceMock);
        config.setAllowIcmp(false);

        try {
            config.saveKuraChains();
        } catch (KuraIOException e) {
            // Expected if file operations fail
        }

        // Verify ICMP rules are configured for disallowing ICMP
        File tempFile = new File(config.getFirewallConfigTmpFileName());
        if (tempFile.exists()) {
            try (Stream<String> lines = Files.lines(tempFile.toPath())) {
                boolean foundDropRule = lines.anyMatch(line -> line.contains("icmp") && line.contains("DROP"));
                assertTrue("Should contain ICMP DROP rule when ICMP is disallowed", foundDropRule);
            }
            Files.deleteIfExists(tempFile.toPath());
        }
    }

    @Test
    public void testRestoreWithInvalidFileContent() throws KuraException, IOException {
        IptablesConfig config = new IptablesConfig() {
            @Override
            public String getFirewallConfigFileName() {
                return getFirewallConfigTmpFileName();
            }
        };

        // Create a file with invalid iptables content
        String invalidContent = "*filter\n" +
                ":INPUT DROP [0:0]\n" +
                "-A invalid-chain-name-that-causes-parsing-error\n" +
                "COMMIT\n";

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(config.getFirewallConfigTmpFileName()))) {
            writer.write(invalidContent);
        }

        try {
            // The restore method should not throw an exception for invalid content
            // It should just silently fail to parse invalid rules
            config.restore();

            // Verify that no valid rules were parsed from the invalid content
            assertTrue("Local rules should be empty after parsing invalid content", config.getLocalRules().isEmpty());
            assertTrue("Port forward rules should be empty after parsing invalid content",
                    config.getPortForwardRules().isEmpty());
            assertTrue("NAT rules should be empty after parsing invalid content", config.getNatRules().isEmpty());
            assertTrue("Auto NAT rules should be empty after parsing invalid content",
                    config.getAutoNatRules().isEmpty());
        } finally {
            File tempFile = new File(config.getFirewallConfigTmpFileName());
            Files.deleteIfExists(tempFile.toPath());
        }
    }

    @Test
    public void testGetIptablesCommand() {
        IptablesConfig config = new IptablesConfig();
        String command = config.getIptablesCommand();

        assertNotNull("iptables command should not be null", command);
        assertTrue("iptables command should contain 'iptables'", command.contains("iptables"));
    }

    @Test
    public void testProtectedMethods() {
        IptablesConfig config = new IptablesConfig() {
            // Override to make protected methods accessible for testing
            @Override
            protected String getIptablesCommand() {
                return super.getIptablesCommand();
            }

            @Override
            protected String[] getAllowIcmp() {
                return super.getAllowIcmp();
            }

            @Override
            protected String[] getNotAllowIcmp() {
                return super.getNotAllowIcmp();
            }
        };

        assertNotNull("getIptablesCommand should not return null", config.getIptablesCommand());
        assertNotNull("getAllowIcmp should not return null", config.getAllowIcmp());
        assertNotNull("getNotAllowIcmp should not return null", config.getNotAllowIcmp());

        assertTrue("getAllowIcmp should return non-empty array", config.getAllowIcmp().length > 0);
        assertTrue("getNotAllowIcmp should return non-empty array", config.getNotAllowIcmp().length > 0);
    }

    @Test
    public void testSaveKuraChainsFileMoving() throws KuraException, IOException {
        setUpMock();

        // Create a temporary config that we can control file paths for
        IptablesConfig config = new IptablesConfig(executorServiceMock) {
            private String tempFileName = System.getProperty("java.io.tmpdir") + "/test-iptables-"
                    + System.currentTimeMillis() + ".tmp";
            private String configFileName = System.getProperty("java.io.tmpdir") + "/test-iptables-"
                    + System.currentTimeMillis() + ".conf";

            @Override
            public String getFirewallConfigTmpFileName() {
                return tempFileName;
            }

            @Override
            public String getFirewallConfigFileName() {
                return configFileName;
            }
        };

        config.saveKuraChains();

        // Verify the final config file was created (temp file was moved)
        File finalConfigFile = new File(config.getFirewallConfigFileName());
        assertTrue("Final config file should exist", finalConfigFile.exists());

        // Verify temp file was moved (no longer exists)
        File tempFile = new File(config.getFirewallConfigTmpFileName());
        assertFalse("Temp file should not exist after move", tempFile.exists());

        // Clean up
        Files.deleteIfExists(finalConfigFile.toPath());
    }

}
